{{- if not .Values.externalSecrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "f5xc-prom-exporter.fullname" . }}-secret
  labels:
    {{- include "f5xc-prom-exporter.labels" . | nindent 4 }}
type: Opaque
stringData:
  F5XC_TENANT_URL: {{ .Values.f5xc.tenantUrl | quote }}
  F5XC_ACCESS_TOKEN: {{ .Values.f5xc.accessToken | quote }}
{{- end }}